### ISSUE TITLE
App crashing on run

### ISSUE THREAD

**Issue by apoorv9990** [dhis2/dhis2-android-datacapture#14]
When i try to run the app it crashes with the following exception

```
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime: FATAL EXCEPTION: main
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime: Process: org.hisp.dhis.android.datacapture, PID: 27237
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime: java.lang.RuntimeException: Unable to create application org.hisp.dhis.android.datacapture.DataCaptureApplication: java.lang.IllegalArgumentException: mapper object must not be null
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4962)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:155)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5725)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException: mapper object must not be null
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.models.utils.Preconditions.isNull(Preconditions.java:38)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.persistence.models.common.base.AbsStore.<init>(AbsStore.java:47)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.persistence.models.common.state.StateStore.<init>(StateStore.java:88)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.persistence.common.Models.<init>(Models.java:163)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.persistence.common.Models.init(Models.java:239)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.core.api.Dhis2.<init>(Dhis2.java:64)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.sdk.core.api.Dhis2.init(Dhis2.java:85)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at org.hisp.dhis.android.datacapture.DataCaptureApplication.onCreate(DataCaptureApplication.java:45)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4959)
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:155) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5725) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030) 
01-16 18:19:41.373 27237-27237/org.hisp.dhis.android.datacapture E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825) 
```

I am trying to debug the app to find out how to use the SDK. What should I do to get the app running?

**Comment by arazabishov** [comment]
This is issue of DHIS2 android SDK rather than DataCapture application. The problem is that now we are refactoring both SDK and apps. As the result, some parts of both are not working as expected.
